### ISSUE TITLE
Implement install page updates based on user feedback

### ISSUE THREAD

**Issue by kristinashu** [mozilla/goggles.webmaker.org#255]
Feedback in https://github.com/mozilla/goggles.webmaker.org/issues/253

Comp: https://redpen.io/p/qv1c96b69ffec76998

Assets:
https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLa0lNNjVVLWYwYWc&usp=sharing

**Comment by Pomax** [comment]
implemented and running on staging: https://x-ray-goggles-staging.herokuapp.com/

**Comment by hannahkane** [comment]
Will test more thoroughly soon, but wanted to file one quick thing: "Firefox" is spelled wrong in step 1.

**Comment by Pomax** [comment]
You don't use forefox? O_o

**Comment by hannahkane** [comment]
No, but I <3 Firefax!

**Comment by kristinashu** [comment]
@Pomax few little things:

PNG is slightly higher than the blue background:

<img width="294" alt="screen shot 2015-12-02 at 9 57 01 am" src="https://cloud.githubusercontent.com/assets/1068783/11539342/6bb0cc66-98db-11e5-854b-a18b70be7291.png">


Activity images aren't loading for me:

<img width="1182" alt="screen shot 2015-12-02 at 9 57 13 am" src="https://cloud.githubusercontent.com/assets/1068783/11539331/5f4d0372-98db-11e5-8367-86af830f995e.png">


If you need the images, they are here: https://drive.google.com/open?id=0B2irLVDJivhLX1BHbG1CQ1B3Zkk

Layout starts to break at narrower widths, are you planning to make it more responsive? Let me know if you want me to mock up an in between desktop and mobile state. 

<img width="918" alt="screen shot 2015-12-02 at 10 11 21 am" src="https://cloud.githubusercontent.com/assets/1068783/11539876/4cae2df6-98de-11e5-988c-3a65b70441e0.png">
<img width="914" alt="screen shot 2015-12-02 at 10 11 30 am" src="https://cloud.githubusercontent.com/assets/1068783/11539878/4cb0b896-98de-11e5-983f-354392b0c1ec.png">
<img width="915" alt="screen shot 2015-12-02 at 10 11 41 am" src="https://cloud.githubusercontent.com/assets/1068783/11539879/4cb38828-98de-11e5-9410-009c2b0483b3.png">
<img width="892" alt="screen shot 2015-12-02 at 10 12 15 am" src="https://cloud.githubusercontent.com/assets/1068783/11539877/4caf253a-98de-11e5-9526-cbc625cda5f0.png">

**Comment by Pomax** [comment]
can you recheck the image alignment and remix images? I've pushed an update for the less files that should fix both

**Comment by Pomax** [comment]
filed the responsiveness as #260

**Comment by kristinashu** [comment]
Remixes are loading now but the forest image is still showing a little blue at the bottom.

**Comment by kristinashu** [comment]
Fixed and closing.
